steps:
  # Membuat image dengan perintah "cloud build -t gcr.io/$PROJECT_ID/notes-123230171-be ."
  # Project ID akan secara otomatis terisi ketika melakukan deploy di project yg dipilih
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/notes-123230171-be", "."]

  # Meng-upload/push image yg telah dibuat ke Artifact Registry
  # Pada bagian ini, dijalankan perintah "docker push 'gcr.io/$PROJECT_ID/notes-123230171-be'"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/notes-123230171-be"]

  # Melakukan deploy ke cloud run menggunakan image yg telah di-upload/push pada langkah sebelumnya
  # Pada bagian ini, dijalankan perintah sebagai berikut.
  # "gcloud run deploy notes-123230171-be \
  #       --image 'gcr.io/$PROJECT_ID/notes-123230171-be \
  #       --timeout 1000s \
  #       --port 3000 \
  #       --region us-central1 \
  #       --allow-unauthenticated' \
  #
  # Keterangan:
  # "gcloud run deploy notes-123230171-be": Perintah yang digunakan untuk mendeploy service ke cloud run dengan nama "notes-123230171-be"
  # "--image 'gcr.io/$PROJECT_ID/notes-123230171-be'": Image yang akan di-deploy
  # "--timeout 1000s": Mengatur waktu maksimum loading menjadi 1000s
  # "--port 3000": Mengatur port yang akan digunakan (disamakan dengan port yg di-listen oleh server)
  # "--region us-central1": Memilih us-central1 sebagai region yg akan digunakan pada cloud run
  # "--allow-unauthenticated": Agar BE dapat diakses di mana saja tanpa memerlukan autentikasi
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "notes-123230171-be",
        "--image",
        "gcr.io/$PROJECT_ID/notes-123230171-be",
        "--timeout",
        "1000s",
        "--port",
        "3000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY
